name: dfm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.7.1
  - pytorch==1.7.1
  - torchvision==0.8.2
  - cudatoolkit=11.0
  - matplotlib==3.3.4
  - pillow==8.2.0
  - opencv==3.4.2
  - ipykernel == 5.3.4
  - pyyaml == 5.4.1
